"""
Parallel Heatwave Analysis Orchestrator.

This script performs high-performance parallel processing of heatwave events
across multiple regions using MPI (Message Passing Interface).

It is designed to work in conjunction with the `core_heatwave` library.
The workflow follows a "Load-Split-Process-Gather" pattern:
1.  **Load:** All processors read the input dataset.
2.  **Split:** The list of regions is divided equally among available processors.
3.  **Process:** Each processor calculates heatwaves for its assigned regions independently.
4.  **Gather:** Results are sent back to the Master Node (Rank 0) for consolidation.

Usage:
    Run this script using `mpiexec` or `mpirun`:
    
    $ mpiexec -n <number_of_cores> python heatwave_mpi.py

    Example (8 cores):
    $ mpiexec -n 8 python heatwave_mpi.py

Dependencies:
    - mpi4py
    - core_heatwave.py (Must be in the same directory)
"""

import sys
import os
import pandas as pd
import numpy as np
from mpi4py import MPI

# ---------------------------------------------------------
# 1. IMPORT SETUP
# ---------------------------------------------------------
# Ensure Python finds the custom module in the current directory
sys.path.append(os.getcwd())

try:
    from core_heatwave import HeatwaveDetector
except ImportError:
    print("❌ Error: 'core_heatwave.py' not found. Please ensure the file is in the same directory.")
    sys.exit(1)

# ---------------------------------------------------------
# 2. CONFIGURATION
# ---------------------------------------------------------
# Input/Output paths
INPUT_FILE = "results_rj_municipalities.csv"  # The CSV generated by the extraction step
OUTPUT_DIR = "outputs"                        # Folder to save final consolidated results

# Analysis Parameters
VAR_NAME = "t2m"                              # Variable column name in the CSV
DATE_COL = "time"                             # Date column name in the CSV
PERCENTILES = [80, 90, 95]                    # Thresholds for heatwave detection

# Climatology Baseline
# Set to None to use the full history available in the CSV as the baseline.
# Example format if needed: (1980, 2010)
REF_PERIOD = None 

# ---------------------------------------------------------
# 3. MPI INITIALIZATION
# ---------------------------------------------------------
comm = MPI.COMM_WORLD
rank = comm.Get_rank()  # Current process ID (0, 1, 2...)
size = comm.Get_size()  # Total number of processes

def main():
    """
    Main execution loop for parallel heatwave detection.
    """
    
    # --- Step A: Preparation (Only Rank 0 creates directories) ---
    # We must ensure the output directory exists before any worker tries to save (if applicable).
    # Only Rank 0 performs this to avoid race conditions (multiple processes trying to create the folder).
    if rank == 0:
        if not os.path.exists(OUTPUT_DIR):
            try:
                os.makedirs(OUTPUT_DIR)
                print(f"[Rank 00] Directory '{OUTPUT_DIR}' created.")
            except FileExistsError:
                pass
    
    # SYNCHRONIZATION BARRIER
    # Ensures no process starts working until Rank 0 has finished the setup.
    comm.Barrier()

    # --- Step B: Data Loading & Workload Distribution ---
    try:
        # Strategy: Replicated Read.
        # Since CSV files are generally small (< few GBs), it is efficient for 
        # every rank to load the dataframe into memory and then filter what they need.
        df_all = pd.read_csv(INPUT_FILE)
        
        # Determine the region column dynamically (handles variations in input naming)
        region_col = 'region' if 'region' in df_all.columns else 'subregion_name'
        
        # Get unique list of regions to process
        all_regions = df_all[region_col].unique()
        
        # SCATTER LOGIC:
        # Split the array of region names into 'size' chunks.
        # 'my_regions' will contain only the subset assigned to this specific Rank.
        my_regions = np.array_split(all_regions, size)[rank]
        
        if rank == 0:
            print(f"[Rank 00] Starting processing of {len(all_regions)} regions across {size} processes.")

    except Exception as e:
        print(f"[Rank {rank:02d}] ❌ CRITICAL LOAD ERROR: {e}")
        sys.exit(1)

    # Barrier to ensure all ranks have loaded data successfully before heavy processing begins
    comm.Barrier()

    # --- Step C: Processing Loop (The Heavy Lifting) ---
    
    local_events_list = []
    local_metrics_list = []

    for i, region in enumerate(my_regions):
        try:
            # Progress Logger (prints every 10 regions to avoid console spam)
            if i == 0 or (i + 1) % 10 == 0:
                print(f"[Rank {rank:02d}] Processing {i+1}/{len(my_regions)} → {region}")

            # 1. Filter data for the specific region
            df_region = df_all[df_all[region_col] == region].copy()

            # 2. Instantiate the detector from the custom library
            detector = HeatwaveDetector(
                df=df_region, 
                variable=VAR_NAME, 
                date_col=DATE_COL, 
                reference_period=REF_PERIOD
            )

            # 3. Run analysis
            # Returns two dataframes: detailed events and summary metrics
            events_df, metrics_df = detector.analyze(percentiles=PERCENTILES)

            # 4. Organize results (only if events were detected)
            if not events_df.empty:
                
                # Tag the data with the region name
                metrics_df['region'] = region
                events_df['region'] = region
                
                # Column Reordering: Ensure 'region' is the first column for readability
                cols_metrics = ['region'] + [c for c in metrics_df.columns if c != 'region']
                metrics_df = metrics_df[cols_metrics]
                
                cols_events = ['region'] + [c for c in events_df.columns if c != 'region']
                events_df = events_df[cols_events]

                # Store in local memory
                local_events_list.append(events_df)
                local_metrics_list.append(metrics_df)

        except Exception as e:
            # If one region fails, log it but don't crash the whole pipeline
            print(f"[Rank {rank:02d}] ❌ ERROR in {region}: {e}")
            continue

    # --- Step D: Consolidation (Gather) ---
    
    # Concatenate local results for this rank
    if local_events_list:
        my_events_concat = pd.concat(local_events_list, ignore_index=True)
        my_metrics_concat = pd.concat(local_metrics_list, ignore_index=True)
    else:
        # Create empty DFs if this rank found no heatwaves
        my_events_concat = pd.DataFrame()
        my_metrics_concat = pd.DataFrame()

    print(f"[Rank {rank:02d}] Finished. Waiting for consolidation...")
    
    # GATHER:
    # Sends 'my_events_concat' from every rank to Rank 0.
    # Rank 0 receives a list of DataFrames (one from each rank).
    all_events_gathered = comm.gather(my_events_concat, root=0)
    all_metrics_gathered = comm.gather(my_metrics_concat, root=0)

    # --- Step E: Final Saving (Rank 0 Only) ---
    if rank == 0:
        print("-" * 50)
        print("Consolidating data from all processors...")

        # Check if we have any data across all ranks
        # The generator expression checks if at least one DF is not empty
        has_data = any(not df.empty for df in all_events_gathered)

        if has_data:
            final_events = pd.concat(all_events_gathered, ignore_index=True)
            final_metrics = pd.concat(all_metrics_gathered, ignore_index=True)
            
            # Save final results to CSV
            path_events = os.path.join(OUTPUT_DIR, "GLOBAL_EVENTS.csv")
            path_metrics = os.path.join(OUTPUT_DIR, "GLOBAL_METRICS.csv")
            
            final_events.to_csv(path_events, index=False)
            final_metrics.to_csv(path_metrics, index=False)
            
            print(f"✅ SUCCESS! Files generated:")
            print(f"   1. {path_events} ({len(final_events)} events)")
            print(f"   2. {path_metrics} ({len(final_metrics)} summary rows)")
        else:
            print("⚠️ WARNING: No heatwave events were detected in any region.")
            print("   No output files were created.")
            
        print("-" * 50)

if __name__ == "__main__":
    main()